#!/bin/bash

if [ ! -d '/tmp/session' ]; then
  mkdir -p /tmp/session
fi

# list runtime libs
dirs=$(echo "$LD_LIBRARY_PATH" | tr ":" "\n")
opt_lib=/opt/lib
dirs=${dirs[@]/$opt_lib/}
for dir in $dirs; do
  ls $dir/*so*
done

if [ -f "/var/task/bootstrap" ]; then
  echo "Found and Running '/var/task/bootstrap' instead of '/opt/bootstrap'"
  exec -- /var/task/bootstrap
else
  echo "Running '/opt/bootstrap' when not found '/var/task/bootstrap'"
  /opt/php/bin/php-fpm --force-stderr
  exec /opt/nginx/bin/nginx -g "daemon off;"
fi
