#!/usr/bin/env bash

set -e

usage() {
  echo "usage: $0 COMMAND"
  echo
  echo "Manage runtime tarball lifecycle."
  echo
  echo "Commands:"
  echo "   copy_libs"
  echo "   clean_libs"
  echo "   zip_layer"
  echo "   php_enable_extensions"
  echo "   php_copy_libs"
  echo "   php_release"
  echo
}

php_copy_libs() {
  rm -rf /opt/lib/*

  for file in $(ls /opt/php/extensions/*.so); do
    copy_libs "$file"
  done

  copy_libs /opt/nginx/bin/nginx
  copy_libs /opt/php/bin/php
  copy_libs /opt/php/bin/php-fpm
}

copy_libs() {
  mkdir -p /opt/lib
  echo "Copy libraries: $1"
  chmod +x "$1"
  for lib in $(ldd "$1"); do
    if [ -f "$lib" ]; then
      echo "cp $lib"
      cp "$lib" /opt/lib
    fi
  done
}

clean_libs() {
  dirs=$(echo "$LD_LIBRARY_PATH" | tr ":" "\n")
  opt_lib=/opt/lib
  dirs=${dirs[@]/$opt_lib/}
  for dir in $dirs; do
    echo "$dir"
    for lib in $(ls /opt/lib); do
      if [ -f "$dir/$lib" ]; then
        echo "rm /opt/lib/$lib because already exists in $dir/$lib"
        rm -rf "/opt/lib/$lib"
      fi
    done
  done
}

zip_layer() {
  echo "zip starting..."
  cd /opt
  zip --quiet --recurse-paths /layer.zip .
  echo "Lambda Layer file is $(du -sh /layer.zip)"
}

php_enable_extensions() {

  echo 'Enable Extensions'
  mkdir -p /opt/php/php.d/

  extension_arr=()

  for so in $(ls /opt/php/extensions/*.so); do
    if readelf --wide --syms $so | grep -q ' zend_extension_entry$'; then
      line="zend_extension=$so"
    else
      line="extension=$so"
    fi
    extension_arr+=($line)
  done

  echo "extension_dir=/opt/php/extensions" >/opt/php/php.d/extensions.ini
  echo ${extension_arr[*]} | tr ' ' '\n' | sort -n >>/opt/php/php.d/extensions.ini
  cat /opt/php/php.d/extensions.ini
}

case "$1" in

php_enable_extensions)
  php_enable_extensions
  ;;

php_copy_libs)
  php_copy_libs
  ;;

copy_libs)
  copy_libs "$2"
  ;;

clean_libs)
  clean_libs
  ;;

zip_layer)
  zip_layer
  ;;

php_release)
  php_enable_extensions
  php_copy_libs
  ;;

*)
  usage
  ;;

esac
