#!/bin/bash

if [ -f "/var/task/bootstrap" ]; then
  echo "Found and Running '/var/task/bootstrap' instead of '/opt/bootstrap'"
  exec -- /var/task/bootstrap
else
  echo "Running '/opt/bootstrap' when '/var/task/bootstrap' not found"
  exec /opt/nginx/bin/nginx -g "daemon off;"
fi
